exclude: "node_modules|migrations|.venv|tests/dev/|tests/fixtures/"

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language: python
        types: [python]
        args: ["--select=E9,F63,F7,F82"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args:
          [
            "--config",
            ".markdownlint.json",
            "--ignore-path",
            ".markdownlintignore",
            "--fix",
            "content",
          ]
        language: node
        # language_version: "14.17.6"
        pass_filenames: true
        types: [file, markdown, non-executable]

# Specific part for https://pre-commit.ci
ci:
  autofix_commit_msg: "[pre-commit.ci] Corrections automatiques appliquées par les git hooks."
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] Mise à jour des git hooks."
  autoupdate_schedule: monthly
  skip: [
      "check-hooks-apply",
      # "markdownlint"
    ]
  submodules: false
