social:
  - icon: "fontawesome/solid/rss"
    link: "https://contribuer.geotribu.fr/feed_rss_created.xml"
    name: "S'abonner aux nouveaux contenus via RSS"
  - icon: "fontawesome/brands/github-alt"
    link: "https://github.com/geotribu/"
    name: "L'organisation Github de Geotribu"
  - icon: "fontawesome/brands/mastodon"
    link: https://mapstodon.space/@geotribu
    name: "Geotribu sur Mapstodon"
  - icon: "fontawesome/brands/linkedin"
    link: https://www.linkedin.com/company/geotribu/
    name: "Les contenus de Geotribu sur LinkedIn"
  - icon: "fontawesome/brands/youtube"
    link: https://www.youtube.com/@geotribu
    name: "Chaîne Youtube de Geotribu"
  - icon: "fontawesome/brands/facebook"
    link: "https://fr-fr.facebook.com/geotribu/"
    name: "Page Facebook de Geotribu"
  - icon: "fontawesome/brands/mailchimp"
    link: http://eepurl.com/hL0zVr
    name: "Abonnez-vous à la newsletter"
  - icon: fontawesome/solid/paper-plane
    link: mailto:<geotribu@gmail.com>
    name: "Nous contacter"
  - icon: "fontawesome/solid/piggy-bank"
    link: https://fr.tipeee.com/geotribu
    name: "Le pot commun sur Tipee"
