git-committers:
  enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_COMMITTERS, false]
  branch: main
  cache_dir:
    !ENV [
      MKDOCS_PLUGIN_GIT_COMMITTERS_CACHE_DIR,
      .cache/plugins/git-committers/,
    ]
  docs_path: content/
  repository: geotribu/site-contribuer
  token:
    !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY", !ENV ["GH_TOKEN_MATERIAL_INSIDERS"]]
